name: picpay
description: PicPay E-Commerce API for Dart and Flutter for create Payments and check Payment status
version: 1.1.1
homepage: https://github.com/stackingwidgets/picpay-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  pedantic: any
  effective_dart: ^1.2.0
